"""Inicializar banco de dados

Revision ID: 308712728977
Revises: 
Create Date: 2024-11-17 13:14:41.589425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308712728977'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prontuario')
    op.drop_table('paciente')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paciente',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=120), nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=11), nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=15), nullable=True),
    sa.Column('endereco', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('prontuario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data', sa.DATE(), nullable=False),
    sa.Column('diagnostico', sa.VARCHAR(length=255), nullable=True),
    sa.Column('prescricoes', sa.VARCHAR(length=255), nullable=True),
    sa.Column('paciente_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
